image: Visual Studio 2019

init:
- git config --global core.autocrlf true

environment:
  DOTNET_VERSION: 5.0.100

build_script:
- ps: ci\build.ps1 

test_script:
- ps: ci\test.ps1

artifacts:
- path: artifacts\*.nupkg

deploy:
- provider: NuGet
  server: https://www.myget.org/F/domaindrivendev/api/v2
  on:
    branch: master
    appveyor_repo_tag: false
  api_key:
    secure: 9QrW8KWCDr8G2ufmOX4O7U4yjneFOYY+5h+auICuWYb1YPaKpQBtUVqrRExg8VXR
  skip_symbols: true

- provider: NuGet
  server: https://www.nuget.org/api/v2/package
  on:
    branch: master
    appveyor_repo_tag: true
  api_key:
    secure: c+ijZg1Q/DtcWvEQgI5UPmCbf0mG68E352Q3s3wn5FakjZ8a0gTBB3WnEX5Hu1TN
  skip_symbols: true
