name: update-dotnet-sdk

on:
  schedule:
    - cron:  '0 10 * * WED'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  update-dotnet-sdk:
    uses: martincostello/update-dotnet-sdk/.github/workflows/update-dotnet-sdk.yml@758e92b362c4164925583874878423a794cce239 # v3.4.1
    permissions:
      contents: write
      pull-requests: write
    with:
      labels: 'dependencies,.NET'
      update-nuget-packages: false
    secrets:
      repo-token: ${{ secrets.GITHUB_TOKEN }}

  add-security-label:
    needs: update-dotnet-sdk
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    if : |
      needs.update-dotnet-sdk.outputs.sdk-updated =='true' &&
      needs.update-dotnet-sdk.outputs.security == 'true'
    steps:
    - name: Add security label
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh pr edit "${{ needs.update-dotnet-sdk.outputs.pull-request-html-url }}" --add-label security
